// array of objects that have a name (team name) and icon (image of logo)
const teams = [
    {name: "Atlanta Hawks", logo: "atlantaHawks.png"},
    {name: "Boston Celtics", logo: "bostonCeltics.png"},
    {name: "Brooklyn Nets", logo: "brooklynNets.png"},
    {name: "Charlotte Hornets", logo: "charlotteHornets.png"},
    {name: "Chicago Bulls", logo: "chicagoBulls.png"},
    {name: "Cleveland Cavaliers", logo: "clevelandCavaliers.png"},
    {name: "Dallas Mavricks", logo: "dallasMavs.png"},
    {name: "Denver Nuggets", logo: "denverNuggets.png"},
    {name: "Detroit Pistons", logo: "detroitPistons.png"},
    {name: "Golden State Warriors", logo: "goldenStateWarriors.png"},
    {name: "Houston Rockets", logo: "houstonRockets.png"},
    {name: "Indiana Pacers", logo: "indianaPacers.png"},
    {name: "Los Angeles Clippers", logo: "LAClippers.png"},
    {name: "Los Angeles Lakers", logo: "LALakers.png"},
    {name: "Memphis Grizzlies", logo: "memphisGrizzlies.png"},
    {name: "Miami Heat", logo: "miamiHeat.png"},
    {name: "Milwaukee Bucks", logo: "milwaukeeBucks.png"},
    {name: "Minnesota TimberWolves", logo: "minnesotaTimberWolves.png"},
    {name: "New Orleans Pelicans", logo: "NOPelicans.png"},
    {name: "New York Knicks", logo: "NYKnicks.png"},
    {name: "Oklahoma City Thunder", logo: "OKCThunder.png"},
    {name: "Orlando Magic", logo: "OrlandoMagic.png"},
    {name: "Pheonix Suns", logo: "PheonixSuns.png"},
    {name: "Philadelphia 76ers", logo: "Philadelphia76ers.png"},
    {name: "Portland TrailBlazers", logo: "portlandTrailBlazers.png"},
    {name: "Sacramento Kings", logo: "SacKings.png"},
    {name: "San Antonio Spurs", logo: "SASpurs.png"},
    {name: "Toronto Raptors", logo: "torontoRaptors.png"},
    {name: "Utah Jazz", logo: "utahJazz.png"},
    {name: "Washington Wizards", logo: "washingtonWizards.png"},
]

export default teams;